[package]
name = "punch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = "4.4.7"
dirs = "5.0.1"
rusqlite = { version = "0.29.0", features = ["chrono"]}
